import type { TabMeta } from "./types";
import type { RemoteAskAnswer, RemoteProjectView, RemoteSessionView, RemoteTabOpenOptions, RemoteTabSnapshot } from "./remoteTypes";

export interface RemoteProjectBindings {
  AddRemoteProject(hostId: string, workspace: string): Promise<RemoteProjectView>;
  RemoveRemoteProject(hostId: string, workspace: string): Promise<void>;
  ListRemoteProjects(): Promise<RemoteProjectView[]>;
  OpenRemoteProjectTab(hostId: string, workspace: string, opts?: RemoteTabOpenOptions): Promise<TabMeta>;
  RemoteProjectSessions(hostId: string, workspace: string): Promise<RemoteSessionView[]>;
  EnsureRemoteProjectSessions(hostId: string, workspace: string): Promise<RemoteSessionView[]>;
  SetRemoteSessionPinned(hostId: string, workspace: string, name: string, pinned: boolean): Promise<void>;
  SetRemoteProjectTitle(hostId: string, workspace: string, title: string): Promise<void>;
  RenameRemoteProjectSession(hostId: string, workspace: string, name: string, title: string): Promise<void>;
  DeleteRemoteProjectSession(hostId: string, workspace: string, name: string): Promise<void>;
  CloseRemoteTab(tabId: string): Promise<void>;
  SubmitRemoteTab(tabId: string, text: string): Promise<void>;
  ClearRemoteTabSession(tabId: string): Promise<void>;
  CancelRemoteTab(tabId: string): Promise<void>;
  ReclaimRemoteTabSession(tabId: string): Promise<void>;
  ApproveRemoteTab(tabId: string, callId: string, decision: string): Promise<void>;
  ResolveRemoteTabPlanDecision(tabId: string, callId: string, action: "start_execution" | "revise_plan" | "exit_plan", feedback: string): Promise<void>;
  AnswerRemoteTab(tabId: string, callId: string, answers: RemoteAskAnswer[]): Promise<void>;
  SubmitRemoteTabExtensionForm(tabId: string, pluginId: string, surfaceId: string, values: Record<string, unknown>): Promise<void>;
  SetRemoteTabModel(tabId: string, ref: string): Promise<void>;
  RewindRemoteTab(tabId: string, checkpointId: string, scope: string): Promise<void>;
  SetRemoteTabComposerProfile(tabId: string, collaborationMode: string, toolApprovalMode: string, goal: string): Promise<string[]>;
  SetRemoteTabToolApprovalMode(tabId: string, mode: string): Promise<void>;
  SetRemoteTabGoal(tabId: string, goal: string): Promise<void>;
  RemoteTabSnapshot(tabId: string): Promise<RemoteTabSnapshot>;
  RemoteTabStatus(tabId: string): Promise<unknown>;
  SetRemoteTabEffort(tabId: string, level: string): Promise<void>;
  SetRemoteTabQualityFloor(tabId: string, floor: string): Promise<void>;
  PauseRemoteTabGoal(tabId: string): Promise<void>;
  ResumeRemoteTabGoal(tabId: string): Promise<void>;
  CancelRemoteTabJobs(tabId: string, jobIds: string[]): Promise<void>;
  SteerRemoteTab(tabId: string, input: string): Promise<void>;
  SetRemoteTabPlanMode(tabId: string, on: boolean): Promise<void>;
  CompactRemoteTab(tabId: string, instructions: string): Promise<void>;
  ReplayRemoteTabPrompts(tabId: string): Promise<unknown>;
  ForkRemoteTab(tabId: string, turn: number, name: string): Promise<void>;
  SummarizeRemoteTab(tabId: string, turn: number, mode: string): Promise<void>;
  ForgetRemoteTab(tabId: string, name: string): Promise<void>;
  RemoteTabBranches(tabId: string): Promise<unknown>;
  RemoteTabSkills(tabId: string): Promise<unknown>;
}
